### ISSUE TITLE
Finder settings

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Rehber#2]
Finder doesn't use saved settings. Open settings and make some changes.

They are modified in localStorage.settings:
`{"arabic":25,"translation":12,"colour":"#00fbff","source":7, ...}`

Reload the page and go to Rehber, sizes are back to default:
`{"arabic":20,"translation":17,"colour":"#00fbff","source":7, ...}`

"Number of Verse in page" is not recorded at all

**Comment by a0m0rajab** [comment]
Font Size storage Fixed. 

To Do: 

- [x] Adding an option to Set Font to default - Better UX. 
- [x] Adding Number Of Verses. - The function is missed.

**Comment by a0m0rajab** [comment]
I have implemented the needed functions!
