### ISSUE TITLE
Context menu in Finder

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Rehber#24]
The issues related to Context menu in mobile devices:
![image](https://user-images.githubusercontent.com/14038292/158098642-0bd4bfcd-764a-4d3a-94dc-2751c923f638.png)
1. The first menu is displayed always in English
2. The selected word in Arabic is hidden below the menu
3. The first menu remains when the second menu is shown

In order to reproduce the problem:
* Select the language TR (or AR)
* Display the translation (mode: "Hepsi")
* Select a word in Arabic, first menu appears
* Select a word in Translation, second menu appears

**Comment by a0m0rajab** [comment]
The context menu was not activated on Tefsir since it does not support the root search, yet in term of consistency we need to add it. 

Beside that the context menu does not support language changes, reported by Alaa Rajab.

**Comment by a0m0rajab** [comment]
related commits:
https://github.com/a0m0rajab/Rehber/commit/1251a85dbb85bca2a44c759a8d7979d5a3e95941
https://github.com/a0m0rajab/Rehber/commit/d0d54be8f702915bdb362e786b9f30544fe78e31
https://github.com/a0m0rajab/Rehber/commit/3d94febe212b03144ec30d4f16d124d6a9ff0751
https://github.com/a0m0rajab/Rehber/commit/16c6c2badc6efb043536dbc793cce5727f36a0a3
https://github.com/a0m0rajab/Rehber/commit/1251a85dbb85bca2a44c759a8d7979d5a3e95941

**Comment by a0m0rajab** [comment]
The issue was reproduced by opening two context menu in the desktop
.
