### ISSUE TITLE
New font: Hafs

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Rehber#3]
The current font (me_quran) was identified as a weakness of Iqra4

We asked Prof Muhammad Abay and he gave the link to a better font.
Changed the font to Hafs version - Quran complex. 

Here is a comparison:
![font compare](https://user-images.githubusercontent.com/14038292/107179015-803fee00-69e6-11eb-94f1-07244e35e83d.png)

We detected this problem: (<s>can be corrected easily</s>)
![font problem](https://user-images.githubusercontent.com/14038292/107179183-ee84b080-69e6-11eb-952e-7f80d209e116.png)

Question: **Is it worth to modify the font?**

**Comment by maeyler** [comment]
Yukarıdaki iki resim açıklama istiyor:

1) iki ayetin _me-quran_ (eski font) ve _Hafs_ (yeni font) ile görünüşü
Sorunlu kelimenin altı çizili ![image](https://user-images.githubusercontent.com/14038292/107180973-f47c9080-69ea-11eb-81b3-9827be791fe9.png)

2) Okunmayan elif üstündeki 'o' işareti farklı bir karakter olmuş

**Comment by maeyler** [comment]
"Okunmayan elif üstündeki 'o' işareti farklı bir karakter olmuş"
Open Finder and select this char and its alif
Do this in the console:
```
s=document.getSelection().toString()
s.charCodeAt(0).toString(16)
s.charCodeAt(1).toString(16)
```
You get "627" and "6df" as desired

[https://en.wikipedia.org/wiki/Arabic_script_in_Unicode](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode#Compact_table)

Conclusion: This font has an incorrect char at [06DF](https://codepoints.net/U+06DF), therefore unusable

**Comment by a0m0rajab** [comment]
For stability we have to use the same source for fonts and text itself. 

Suggestion:
If we want to use the King Fahd Quran Complex Hafs font we have to use their fonts, they have a few resources for that
Fonts: https://fonts.qurancomplex.gov.sa/
Texts:  https://qurancomplex.gov.sa/techquran/dev/

**Comment by a0m0rajab** [comment]
Follow up:
We decided to experiment with Zekr and ZekrBold fonts and compare them with the old me_quran font. 

I did not see any problem for now but the line height, @maeyler what do you think?

**Comment by maeyler** [comment]
Hafs implementation of U06DF is wrong -- so it is not usable
https://codepoints.net/U+06DF
SMALL HIGH ROUNDED ZERO

> We decided to experiment with Zekr and ZekrBold fonts and compare them with
> the old me_quran font.
>
> I did not see any problem for now but the line height, @maeyler
> <https://github.com/maeyler> what do you think?
>
 Zekr looks very nice, yes

**Comment by a0m0rajab** [comment]
Done! 

Added Zekr, ZekrBold fonts, 
we chose the Zekr font as default one, 
Add a function to set the font type.
