### ISSUE TITLE
Searching for an exact word

### ISSUE THREAD

**Issue by imranture** [Okuyun/Rehber#5]
Searching for a word produces results that contain unrelated word(s).

Here is an example:

![searching-for-an-exact-word-issue](https://user-images.githubusercontent.com/1104699/107497047-26a61200-6be6-11eb-8331-9b65fdd1ff5f.png)

Results for the word "judgement" were also listed while looking for the word "judge"

Using quotation marks to search an exact phrase/word should overcome this issue.

**Comment by SmallSimpleSafe** [comment]
Related to this issue: search for [sitta](https://okuyun.github.io/Kuran/#b=sit~a), **istawa** is also hilited

![image](https://user-images.githubusercontent.com/14292061/107726404-dcae5080-6cf9-11eb-920b-ad572cff45d8.png)

**Comment by a0m0rajab** [comment]
The Search algorithm is looking for words with the similar letters without consideration of harakat (vowels in Arabic) or even the case in non-Arabic languages.

The idea was to have higher error tolerance rate for users.

Though, I will add the exact search feature soon.

________________________________

**Comment by a0m0rajab** [comment]
update: working on this issue will take a bit of time - we have to find a symbol that is not used in buckwalter to use it for exact search.

**Comment by maeyler** [comment]
These two searches return the same result:
https://okuyun.github.io/Rehber/finder.html#t=%20biriniz%20
https://okuyun.github.io/Rehber/finder.html#t=biriniz

Apparently, the search string is trimmed. Correction of this bug will resolve the issue reported above.

**Comment by a0m0rajab** [comment]
@maeyler you are right about that, I have solved the issue.

**Comment by maeyler** [comment]
Problem: Results for the word "judgement" were also listed while looking for the word "judge"

Solution: Search " judge " without quotes, with spaces
