### ISSUE TITLE
Font Selection

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Rehber#6]
We can empower the users with font selection feature.

**Comment by maeyler** [comment]
You have already said this <https://github.com/Okuyun/Rehber/issues/2> --
Why a new issue?
[image: image.png]
Font selection was not my concern -- *I need the red part*

**Comment by maeyler** [comment]
You have <a href='https://github.com/Okuyun/Rehber/issues/2'>already said this</a> -- Why a new issue?
![image](https://user-images.githubusercontent.com/14038292/107845207-efed1900-6dea-11eb-907d-6f1e86b6aab9.png)

Font selection was not my concern -- <i>I need the red part</i>

**Comment by a0m0rajab** [comment]
@maeyler I was talking about the font size in the finder settings issue #2 , but this one was for the font type itself, yet it's duplication of New font issue #3
