### ISSUE TITLE
New font: Zekr

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Rehber#7]
Zekr font is better-looking and we observed no problems with Unicode.

Adding [line-height=1.35](https://github.com/Okuyun/Rehber/commit/652e15e) introduced two problems:

1) Arabic mode: a line with selection overwrites previous line (also in mobile)

2) One-line mode: vertical scroll bars for each item (not observed in mobile)

`line-height=1.8` solves the first problem, but scroll bars remain if `line-height<2.1` (default value)

**Comment by a0m0rajab** [comment]
The problem seems to appear only in windows OS. 

I have added a fast fix for it, by: 
- changing the line height to 1.8 (as suggested)
- Changing overflow settings to hidden

I need to check it from a windows system before closing the issue. 

[Commit](https://github.com/Okuyun/Rehber/commit/cc4c577493d4d4b212586e59bf914775e429a9f4)

**Comment by maeyler** [comment]
Thank you Rajab, it is done

**Comment by SmallSimpleSafe** [comment]
Comparison -- left: old font, right: current font Zekr
![illa iblis](https://user-images.githubusercontent.com/14292061/107879207-8c491580-6ee8-11eb-9066-0c766de7e5f4.png)

The user may select either font

**Comment by a0m0rajab** [comment]
The user is able to use both fonts now, the default one is zekr.
Both of them are accessable from: settings -> font type.

Is there any action needed for this issue?
________________________________

**Comment by maeyler** [comment]
Thank you Rajab, it was good progress. I re-open this issue just for completeness. 

Here is the current font dialog:

![font dialog](https://user-images.githubusercontent.com/14038292/107879788-0202b080-6eec-11eb-8760-b0df4f0e6413.png)

**Comment by a0m0rajab** [comment]
That's great to know, I will close the issue then.
